services:
  - type: web
    name: r-dot
    runtime: python3
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput --clear"
    startCommand: "gunicorn R_dot.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        fromService:
          type: web
          name: r-dot
          property: host
      - key: WHITE_NOISE_USE_FINDERS
        value: "True"
      - key: WHITE_NOISE_ROOT
        value: "staticfiles"
