# Generated by Django 5.2.3 on 2025-06-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('customized_jersey', 'Customized Jersey'), ('kids', "Kid's"), ('sports', 'Sports'), ('mens', "Men's")], max_length=50)),
                ('image', models.ImageField(upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('stock_out', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
