# Generated by Django 5.2.6 on 2025-11-21 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_banner_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='category',
        ),
        migrations.AddField(
            model_name='banner',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='main.type'),
        ),
    ]
