# Generated by Django 5.2.6 on 2026-03-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_banner_link_banner_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='neworder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='neworder',
            name='size',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='is_fashion',
            field=models.BooleanField(default=False),
        ),
    ]
